
export const services = [
  {
    id: "mazallat-sayarat-riyadh",
    title: "مظلات سيارات  ",
    shortTitle: "مظلات سيارات",
    description: "مظلات سيارات احترافية   - حماية كاملة من الشمس والأمطار",
    features: [
      "حماية متكاملة من أشعة الشمس UV والأمطار",
      "تقليل درجة حرارة السيارة بشكل كبير",
      "خامات عالية الجودة ومقاومة للعوامل الجوية",
      "تصاميم عصرية تناسب جميع الأذواق",
      "خيارات متعددة: ثابتة، متحركة، مقوسة، هرمية",
      "تركيب احترافي مع ضمان شامل",
    ],
    image: "/newphoto/mdlat_syarat_1.jpg",
    slug: "mazallat-sayarat-riyadh",
  },
  {
    id: "mazallat-mutaharrika-riyadh",
    title: "مظلات متحركة  ",
    shortTitle: "مظلات متحركة",
    description: "مظلات متحركة احترافية   - مرونة وسهولة في الاستخدام",
    features: [
      "سهولة الفتح والإغلاق بأنظمة يدوية أو أوتوماتيكية",
      "تعديل زاوية المظلة حسب أشعة الشمس",
      "حماية سريعة من المطر والشمس",
      "تصاميم عصرية وأنيقة",
      "مناسبة لجميع المساحات",
      "تركيب محترف مع ضمان على النظام الميكانيكي",
    ],
    image: "/img/mdlat_mthrk.jpg",
    slug: "mazallat-mutaharrika-riyadh",
  },
  {
    id: "mazallat-haramiya-riyadh",
    title: "مظلات هرمية  ",
    shortTitle: "مظلات هرمية",
    description: "مظلات هرمية احترافية   - تصميم فريد وجاذبية عالية",
    features: [
      "تصميم هرمي فريد وجذاب",
      "تصريف ممتاز للمياه",
      "متانة عالية ومقاومة للرياح",
      "مناسبة للمساحات المتوسطة والكبيرة",
      "خامات عالية الجودة",
      "تركيب احترافي مع ضمان",
    ],
    image: "/img/mdlat_hrmyh_alryad_3.jpg",
    slug: "mazallat-haramiya-riyadh",
  },
  {
    id: "mazallat-shad-inshai-riyadh",
    title: "مظلات شد إنشائي  ",
    shortTitle: "مظلات شد إنشائي",
    description: "مظلات شد إنشائي احترافية   - متانة وقوة تحمل عالية",
    features: [
      "تصميم بدون عوائق وسطية",
      "قوة تحمل عالية للمساحات الكبيرة",
      "تقنية الشد الإنشائي المتقدمة",
      "مقاومة للرياح والعوامل الجوية",
      "سهولة الصيانة والتنظيف",
      "ضمان على الهيكل والتركيب",
    ],
    image: "/img/mdlat_shd_anshaey_alryad_6.jpg",
    slug: "mazallat-shad-inshai-riyadh",
  },
  {
    id: "mazallat-maqousa-riyadh",
    title: "مظلات مقوسة  ",
    shortTitle: "مظلات مقوسة",
    description: "مظلات مقوسة احترافية   - جمالية ومتينة",
    features: [
      "تصميم مقوس أنيق وجذاب",
      "تصريف ممتاز للمياه",
      "متانة عالية ومقاومة للعوامل الجوية",
      "مناسبة لجميع أنواع المساحات",
      "خامات عالية الجودة",
      "تركيب احترافي مع ضمان",
    ],
    image: "/img/mdlat_mqwsh_alryad_2.jpg",
    slug: "mazallat-maqousa-riyadh",
  },
  {
    id: "mazallat-madaris-riyadh",
    title: "مظلات مدارس  ",
    shortTitle: "مظلات مدارس",
    description: "مظلات مدارس احترافية   - حماية آمنة للطلاب والمعلمين",
    features: [
      "مواد آمنة وغير سامة مناسبة للأطفال",
      "حماية كاملة من الشمس والمطر",
      "تصاميم ملائمة للبيئة المدرسية",
      "تهوية ممتازة",
      "سهولة الصيانة والتنظيف",
      "ضمان على التركيب والمواد",
    ],
    image: "/img/mdlat_mdars_alryad.jpg",
    slug: "mazallat-madaris-riyadh",
  },
  {
    id: "mazallat-masabi-riyadh",
    title: "مظلات مسابح  ",
    shortTitle: "مظلات مسابح",
    description: "مظلات مسابح احترافية   - حماية وخصوصية للمسابح",
    features: [
      "حماية من أشعة الشمس UV",
      "تقليل تبخر الماء",
      "تهوية ممتازة للحفاظ على جودة الهواء",
      "مواد مقاومة للكلور والعوامل الكيميائية",
      "تصميمات جمالية تزيد من جمال المسابح",
      "سهولة التنظيف والصيانة",
    ],
    image: "/img/mdlat_msabh_jmylh.jpg",
    slug: "mazallat-masabi-riyadh",
  },
  {
    id: "sawatr-hadid-riyadh",
    title: "سواتر حديد  ",
    shortTitle: "سواتر حديد",
    description: "سواتر حديد احترافية   - قوة ومتانة لا مثيل لها",
    features: [
      "حديد مجلفن عالي الجودة ومقاوم للصدأ",
      "قوة تحمل عالية للمساحات الكبيرة",
      "تصميمات قوية وآمنة",
      "مناسبة للمستودعات والمنشآت التجارية",
      "متانة طويلة الأمد",
      "تركيب محكم مع ضمان",
    ],
    image: "/newphoto/swatr_hdyd.jpg",
    slug: "sawatr-hadid-riyadh",
  },
  {
    id: "sawatr-laser-riyadh",
    title: "سواتر ليزر  ",
    shortTitle: "سواتر ليزر",
    description: "سواتر ليزر احترافية   - تقنية حديثة وتصميم مبتكر",
    features: [
      "قطع بالليزر لدقة عالية في التصميم",
      "تصاميم معقدة ومخصصة",
      "خامات عالية الجودة",
      "مقاومة للصدأ والعوامل الجوية",
      "سهولة التركيب",
      "ضمان على الجودة والتصميم",
    ],
    image: "/img/swatr_lyzr_hmayh.jpg",
    slug: "sawatr-laser-riyadh",
  },
  {
    id: "sawatr-qumash-riyadh",
    title: "سواتر قماشية  ",
    shortTitle: "سواتر قماشية",
    description: "سواتر قماشية احترافية   - مرونة وجمالية مع توفير الخصوصية",
    features: [
      "قماش عالي الجودة ومقاوم للعوامل الجوية",
      "توفير خصوصية ممتازة",
      "تهوية جيدة",
      "خفة الوزن وسهولة التركيب",
      "تصاميم وألوان متعددة",
      "سهولة التنظيف والصيانة",
    ],
    image: "/img/swatr_qmash_2.jpg",
    slug: "sawatr-qumash-riyadh",
  },
  {
    id: "sawatr-plastic-riyadh",
    title: "سواتر بلاستيك  ",
    shortTitle: "سواتر بلاستيك",
    description: "سواتر بلاستيك احترافية   - عملية وجمالية بتكلفة مناسبة",
    features: [
      "مواد بلاستيكية عالية الجودة ومتينة",
      "مقاومة للصدمات والعوامل الجوية",
      "سهلة التنظيف والصيانة",
      "خيارات ألوان متعددة",
      "تكلفة مناسبة",
      "تركيب سريع وسهل",
    ],
    image: "/img/swatr_blastyk.jpg",
    slug: "sawatr-plastic-riyadh",
  },
  {
    id: "jalsat-borjolat-riyadh",
    title: "جلسات برجولات  ",
    shortTitle: "جلسات برجولات",
    description: "جلسات برجولات احترافية   - تصميم وتغطية جلسات خارجية",
    features: [
      "تصاميم برجولات متنوعة وعصرية",
      "مواد عالية الجودة ومتينة",
      "حماية من الشمس والمطر",
      "إضافة جمالية للمساحات الخارجية",
      "مناسبة للحدائق والشرفات",
      "تركيب احترافي مع ضمان",
    ],
    image: "/newphoto/jlsat_kharjyh.jpg",
    slug: "jalsat-borjolat-riyadh",
  },
  {
    id: "tansiq-hadaiq-riyadh",
    title: "تنسيق حدائق  ",
    shortTitle: "تنسيق حدائق",
    description: "تنسيق حدائق احترافية   - تصميم وتجميل المساحات الخضراء",
    features: [
      "تصميم حدائق مبتكر ومخصص",
      "اختيار النباتات المناسبة للمناخ",
      "أنظمة ري متطورة",
      "إضاءة حدائق جذابة",
      "صيانة دورية",
      "استشارات تصميم مجانية",
    ],
    image: "/img/tnsyq_hdaeyq.jpg",
    slug: "tansiq-hadaiq-riyadh",
  },
  {
    id: "ghoraf-sandwich-panel-riyadh",
    title: "غرف ساندويش بنل  ",
    shortTitle: "غرف ساندويش بنل",
    description: "غرف ساندويش بنل احترافية   - عزل وقوة وتصميم عملي",
    features: [
      "عزل حراري وصوتي ممتاز",
      "مواد عالية الجودة ومقاومة للحريق",
      "تركيب سريع وسهل",
      "تصاميم متنوعة وقابلة للتخصيص",
      "مناسبة للاستخدامات السكنية والتجارية",
      "متانة عالية وصيانة سهلة",
    ],
    image: "/img/sndwsh_bnl_alryad_7.jpg",
    slug: "ghoraf-sandwich-panel-riyadh",
  },
  {
    id: "qaramid-riyadh",
    title: "قراميد  ",
    shortTitle: "قراميد",
    description: "قراميد احترافية   - حماية وجمالية للأسطح",
    features: [
      "تصميمات تقليدية وعصرية",
      "مقاومة للعوامل الجوية",
      "عزل حراري جيد",
      "متانة عالية طويلة الأمد",
      "سهولة التركيب",
      "خيارات ألوان متعددة",
    ],
    image: "/img/qrmyd_alryad_3.jpg",
    slug: "qaramid-riyadh",
  },
  {
    id: "hanajer-w-mastoudat-riyadh",
    title: "هناجر ومستودعات  ",
    shortTitle: "هناجر ومستودعات",
    description: "هناجر ومستودعات احترافية   - مساحات تخزين واسعة ومحمية",
    features: [
      "تصميمات مخصصة لجميع الاحتياجات",
      "مساحات تخزين واسعة وعملية",
      "حماية كاملة من العوامل الجوية",
      "تهوية ممتازة",
      "أبواب وأقفال آمنة",
      "تركيب سريع وضمان",
    ],
    image: "/img/hnajr_alryad_1.jpg",
    slug: "hanajer-w-mastoudat-riyadh",
  },
  {
    id: "buyut-sha3r-riyadh",
    title: "بيوت شعر  ",
    shortTitle: "بيوت شعر",
    description: "بيوت شعر احترافية   - تصميم وcraftsmanship عالية الجودة",
    features: [
      "تصميمات عصرية ومتعددة الاستخدامات",
      "خامات عالية الجودة ومقاومة للعوامل الجوية",
      "تركيب سريع وسهل",
      "مناسبة لجميع المناخات",
      "إمكانية التخصيص حسب الطلب",
      "ضمان شامل على التركيب والمواد",
    ],
    image: "/img/bywt_shar_alryad_bshkl_jmyl_1.jpg",
    slug: "buyut-sha3r-riyadh",
  },
  {
    id: "asatih-sandwich-panel-riyadh",
    title: "أسطح ساندويش بنل  ",
    shortTitle: "أسطح ساندويش بنل",
    description: "أسطح ساندويش بنل احترافية   - عزل وحماية للمباني",
    features: [
      "عزل حراري وصوتي ممتاز",
      "مواد عالية الجودة ومقاومة للحريق",
      "تركيب سريع وسهل",
      "تصاميم متنوعة وقابلة للتخصيص",
      "مناسبة للاستخدامات السكنية والتجارية",
      "متانة عالية وصيانة سهلة",
    ],
    image: "/img/sndwsh_bnl_alryad1.jpg",
    slug: "asatih-sandwich-panel-riyadh",
  },
];
